### ISSUE TITLE
Missing 32x textures of water

### ISSUE THREAD

**Issue by JosefLitos** [Compliance-Resource-Pack/Compliance-Java-32x#10]
in the 1.18 version, there are no signs of water even as a name, but in beta 1.19, you have an emty mcmeta file for water, but still no texture.

**Comment by Pomi108** [comment]
I added all vanilla mcmeta files so that I don't forget to add them in the future when they're needed, and they don't hurt anything since they get ignored by the game when not associated with an image file. This is intentional.
