### ISSUE TITLE
Panorama looks wrong

### ISSUE THREAD

**Issue by Rafii2198** [Compliance-Resource-Pack/Compliance-Java-32x#4]
The panormama in main menu looks weird, like it is cut in some places etc.
I am playing modded but my friend who play just vanilla also noticed it, exactly same errors

![obraz](https://user-images.githubusercontent.com/26695327/147117384-f162a9c3-00a6-4d0b-ab4a-f100bc806d0b.png)
![obraz](https://user-images.githubusercontent.com/26695327/147117580-ab124d61-cdc3-4b5d-90cd-7f1315cf312a.png)

**Comment by RobertRR11** [comment]
This is already fixed on Github, the next release will also include the fix.

I'll close this issue after the next release is published, so hopefully no duplicate issues get opened.

**Comment by RobertRR11** [comment]
This issue is now fixed in Beta 18, you can download it here https://compliancepack.net/compliance32x/B18
