### ISSUE TITLE
Ignore .DS_Store in all directories

### ISSUE THREAD

**Issue by dlee13** [Compliance-Resource-Pack/Compliance-Java-32x#7]
Your `.gitignore` should be
```
**/.DS_Store
```
The `**/` prefix is a pattern that means to match in all directories. https://git-scm.com/docs/gitignore#_pattern_format

**Comment by RobertRR11** [comment]
Sorry for the late reply, but I'm sure that leaving out **/ does the exact same thing?

**Comment by dlee13** [comment]
Leaving that out means it'll only match the `.DS_Store` found at the project root.

**Comment by RobertRR11** [comment]
> Leaving that out means it'll only match the `.DS_Store` found at the project root.

Then what about this?
![image](https://user-images.githubusercontent.com/57044042/151712861-945ca94c-ed8e-4a5a-8994-52ac4df0aa20.png)

**Comment by dlee13** [comment]
Maybe the Github app handles the gitignore differently than cli git.

**Comment by RobertRR11** [comment]
Also just tried out git cli, same result
