### ISSUE TITLE
Please make custom bookshelves as models, not ctm

### ISSUE THREAD

**Issue by JosefLitos** [Compliance-Resource-Pack/Compliance-Java-32x#8]
I am making an addon, where I have 3D design of bookshelves, but ctm overrides models, so the design is not visible.
Could you add the textures as bookshelf models with different textures, please?

**Comment by Pomi108** [comment]
No. We're not changing this just because of one person's add-on.

**Comment by JosefLitos** [comment]
But why, if it was as models, everyone could use it, not just optifine users, your approach seems so invasive.

**Comment by Juknum** [comment]
We are trying to keep the pack as vanilla as possible, so using custom models is against that idea
