### ISSUE TITLE
Use new Minecraft title and Java Edition subtitle

### ISSUE THREAD

**Issue by Poopooracoocoo** [Compliance-Resource-Pack/Compliance-Java-32x#9]
Compliance 32x:
![image](https://user-images.githubusercontent.com/51363864/152819137-8b63b072-206c-44d9-89c2-9477b3879f69.png)

Minecraft Launcher:
![image](https://user-images.githubusercontent.com/51363864/152818389-09db45d1-50e2-4d72-84b2-3b799ede0dcd.png)

**Comment by Poopooracoocoo** [comment]
Would an add-on that adds this be considered?

**Comment by TheRolfFR** [comment]
> Would an add-on that adds this be considered?

Do you want an add-on with the extracted new logo ? Or do you want the new logo but remade in 32x ?

**Comment by Poopooracoocoo** [comment]
I'd say that the extracted new logo would be more fitting considering that the default game has 16px assets and Bedrock Edition has a high res title. :)
